### PR TITLE
Cyclic Bloodmoon

### PR DESCRIPTION
**Pull request by DrParadox7**
Add configuration to make Blood Moons cyclical (disabled by default).

Every X days (configurable) a blood moon will rise.
This  works fine in conjunction with the current chance system but it would likely result in too frequent blood moons.

### CODE REVIEW

**Comment by Dream-Master** [comment]
i would say lets add it.

**Review by Dream-Master — APPROVED** [review]

**Comment by Alastors** [comment]
I don't see the point in this myself?

**Comment by Alastors** [comment]
But as long as it's a config it's fine

**Comment by Dream-Master** [comment]
its set to 0 so no changes so far. But if you want to change it you are now able to do so.

**Comment by Alastors** [comment]
> its set to 0 so no changes so far. But if you want to change it you are now able to do so.

Yeah but my thought is, this is a change that only really effects earlygame if it were ever turned past 0, like severe earlygame, and I really don't see any players saying "oh you know what this run needs? More time where I dig a pit and just hide in the ground while I AFK for 20 minutes"

**Comment by Dream-Master** [comment]
@Alastors you you mean more player set the Blood moon to 0 to avaoid it ? Or what you maen ?

**Comment by eigenraven** [comment]
I assume this PR is for DrParadox's pack, not really intended for GTNH - and the mob balance is different in different packs.

**Comment by Alastors** [comment]
> @Alastors you you mean more player set the Blood moon to 0 to avaoid it ? Or what you maen ?

I mean isn't there already a config to turn blood moons off? 

My point was I don't ever see a time in which players would want to actually cause more blood moons to happen, because they're already just an annoying time to AFK for like 20 minutes instead of actual pack progress related stuff. Just another déterrant from people actually playing the pack.

But yeah like Raven said it's probably not meant for our pack so /shrug I guess

**Comment by Dream-Master** [comment]
this config give us the change or others play the pack say ok every 7 days a blood moon occurs for every x days? If it is set to 0 nothing happen it use the chance value right ?

**Comment by Dream-Master** [comment]
> > @Alastors you you mean more player set the Blood moon to 0 to avaoid it ? Or what you maen ?
> 
> I mean isn't there already a config to turn blood moons off?
> 
> My point was I don't ever see a time in which players would want to actually cause more blood moons to happen, because they're already just an annoying time to AFK for like 20 minutes instead of actual pack progress related stuff. Just another déterrant from people actually playing the pack.
> 
> But yeah like Raven said it's probably not meant for our pack so /shrug I guess

yes there is an option to turn it off

**Comment by Alastors** [comment]
> this config give us the change or others play the pack say ok every 7 days a blood moon occurs for every x days? If it is set to 0 nothing happen it use the chance value right ?

It says you can use both together in the ticket itself

**Comment by Dream-Master** [comment]
yea i just ask the dev and get this confirmed. So this pr have 0 downside for GTNH

**Comment by Alastors** [comment]
> yea i just ask the dev and get this confirmed. So this pr have 0 downside for GTNH

Sure, I suppose, that's why I'm not personally against it, I just don't much see the point (except now with Raven's thought)

**Pull request merged**
